# Ninja Multi-Config: per-configuration module outputs, both configurations
# build into the same tree and run.
include("${CMAKE_CURRENT_LIST_DIR}/Harness.cmake")
fixture_create(diamond multi-module)
fixture_configure(GENERATOR "Ninja Multi-Config" MAKE_PROGRAM "${NINJA}")
fixture_build(out CONFIG Debug)
assert_build_ok(out)
fixture_build(out CONFIG Release)
assert_build_ok(out)
assert_exit("${WORK_DIR}/build/diamond/Debug/diamond" 23)
assert_exit("${WORK_DIR}/build/diamond/Release/diamond" 23)
assert_exit("${WORK_DIR}/build/multi-module/Release/multi" 42)
assert_exists("${WORK_DIR}/build/diamond/CMakeFiles/Base.hylo.dir/Debug/Base.hylomodule" "Debug archive")
assert_exists("${WORK_DIR}/build/diamond/CMakeFiles/Base.hylo.dir/Release/Base.hylomodule" "Release archive")
# Restat pruning works per configuration too.
file(TOUCH_NOCREATE "${WORK_DIR}/src/diamond/Base.hylo")
fixture_build(out CONFIG Release)
assert_build_ok(out)
assert_contains("${out}" "Compiling Hylo module Base (" "touched Base must recompile")
assert_not_contains("${out}" "Compiling Hylo module Left (" "unchanged interface must not recompile Left")
