# hylo-project.json is valid JSON and describes the module graph, including
# imports resolved through target_link_libraries and late-added sources.
include("${CMAKE_CURRENT_LIST_DIR}/Harness.cmake")
fixture_create(diamond plain-targets)
fixture_configure()
set(_manifest "${WORK_DIR}/build/hylo-project.json")
assert_exists("${_manifest}" "manifest not written at generate time")
file(READ "${_manifest}" _json)
string(JSON _n LENGTH "${_json}" modules)
if(NOT _n EQUAL 6)
  message(FATAL_ERROR "expected 6 modules in the manifest, got ${_n}:\n${_json}")
endif()
# Find the MainDiamond entry and check its imports/search paths.
set(_found FALSE)
math(EXPR _last "${_n} - 1")
foreach(_i RANGE ${_last})
  string(JSON _name GET "${_json}" modules ${_i} name)
  if(_name STREQUAL "MainDiamond")
    set(_found TRUE)
    string(JSON _imports GET "${_json}" modules ${_i} imports)
    assert_contains("${_imports}" "\"Left\"" "MainDiamond must import Left")
    assert_not_contains("${_imports}" "\"Base\"" "MainDiamond must not import Base (PRIVATE in Left)")
    string(JSON _paths GET "${_json}" modules ${_i} moduleSearchPaths)
    assert_contains("${_paths}" "Base.hylo.dir" "transitive archive dir must be a search path")
  elseif(_name STREQUAL "Greeter")
    string(JSON _sources GET "${_json}" modules ${_i} sources)
    assert_contains("${_sources}" "GreeterExtra.hylo" "late-added source must be listed")
    string(JSON _archive GET "${_json}" modules ${_i} archive)
    assert_contains("${_archive}" "Greeter.hylomodule" "library must list its archive")
  endif()
endforeach()
if(NOT _found)
  message(FATAL_ERROR "MainDiamond not in manifest:\n${_json}")
endif()
